set(TFLITE_SRC $ENV{TF_PATH}/tensorflow/lite)

add_library(tflite_micro
  ${TFLITE_SRC}/micro/kernels/activations.cc
  ${TFLITE_SRC}/micro/kernels/add.cc
  ${TFLITE_SRC}/micro/kernels/add_n.cc
  ${TFLITE_SRC}/micro/kernels/arg_min_max.cc
  ${TFLITE_SRC}/micro/kernels/batch_to_space_nd.cc
  ${TFLITE_SRC}/micro/kernels/cast.cc
  ${TFLITE_SRC}/micro/kernels/ceil.cc
  ${TFLITE_SRC}/micro/kernels/circular_buffer.cc
  ${TFLITE_SRC}/micro/kernels/comparisons.cc
  ${TFLITE_SRC}/micro/kernels/concatenation.cc
  ${TFLITE_SRC}/micro/kernels/conv.cc
  ${TFLITE_SRC}/micro/kernels/conv_common.cc
  ${TFLITE_SRC}/micro/kernels/cumsum.cc
  ${TFLITE_SRC}/micro/kernels/depth_to_space.cc
  ${TFLITE_SRC}/micro/kernels/depthwise_conv.cc
  ${TFLITE_SRC}/micro/kernels/depthwise_conv_common.cc
  ${TFLITE_SRC}/micro/kernels/dequantize.cc
  ${TFLITE_SRC}/micro/kernels/detection_postprocess.cc
  ${TFLITE_SRC}/micro/kernels/elementwise.cc
  ${TFLITE_SRC}/micro/kernels/elu.cc
  ${TFLITE_SRC}/micro/kernels/ethosu.cc
  ${TFLITE_SRC}/micro/kernels/exp.cc
  ${TFLITE_SRC}/micro/kernels/expand_dims.cc
  ${TFLITE_SRC}/micro/kernels/fill.cc
  ${TFLITE_SRC}/micro/kernels/floor.cc
  ${TFLITE_SRC}/micro/kernels/floor_div.cc
  ${TFLITE_SRC}/micro/kernels/floor_mod.cc
  ${TFLITE_SRC}/micro/kernels/fully_connected.cc
  ${TFLITE_SRC}/micro/kernels/fully_connected_common.cc
  ${TFLITE_SRC}/micro/kernels/gather_nd.cc
  ${TFLITE_SRC}/micro/kernels/hard_swish.cc
  ${TFLITE_SRC}/micro/kernels/kernel_runner.cc
  ${TFLITE_SRC}/micro/kernels/kernel_util.cc
  ${TFLITE_SRC}/micro/kernels/l2norm.cc
  ${TFLITE_SRC}/micro/kernels/l2_pool_2d.cc
  ${TFLITE_SRC}/micro/kernels/leaky_relu.cc
  ${TFLITE_SRC}/micro/kernels/logical.cc
  ${TFLITE_SRC}/micro/kernels/logistic.cc
  ${TFLITE_SRC}/micro/kernels/log_softmax.cc
  ${TFLITE_SRC}/micro/kernels/maximum_minimum.cc
  ${TFLITE_SRC}/micro/kernels/mul.cc
  ${TFLITE_SRC}/micro/kernels/neg.cc
  ${TFLITE_SRC}/micro/kernels/pack.cc
  ${TFLITE_SRC}/micro/kernels/pad.cc
  ${TFLITE_SRC}/micro/kernels/pooling.cc
  ${TFLITE_SRC}/micro/kernels/prelu.cc
  ${TFLITE_SRC}/micro/kernels/quantize.cc
  ${TFLITE_SRC}/micro/kernels/quantize_common.cc
  ${TFLITE_SRC}/micro/kernels/reduce.cc
  ${TFLITE_SRC}/micro/kernels/reshape.cc
  ${TFLITE_SRC}/micro/kernels/resize_bilinear.cc
  ${TFLITE_SRC}/micro/kernels/resize_nearest_neighbor.cc
  ${TFLITE_SRC}/micro/kernels/round.cc
  ${TFLITE_SRC}/micro/kernels/shape.cc
  ${TFLITE_SRC}/micro/kernels/softmax.cc
  ${TFLITE_SRC}/micro/kernels/softmax_common.cc
  ${TFLITE_SRC}/micro/kernels/space_to_batch_nd.cc
  ${TFLITE_SRC}/micro/kernels/split.cc
  ${TFLITE_SRC}/micro/kernels/split_v.cc
  ${TFLITE_SRC}/micro/kernels/squeeze.cc
  ${TFLITE_SRC}/micro/kernels/strided_slice.cc
  ${TFLITE_SRC}/micro/kernels/sub.cc
  ${TFLITE_SRC}/micro/kernels/svdf.cc
  ${TFLITE_SRC}/micro/kernels/svdf_common.cc
  ${TFLITE_SRC}/micro/kernels/tanh.cc
  ${TFLITE_SRC}/micro/kernels/transpose_conv.cc
  ${TFLITE_SRC}/micro/kernels/unpack.cc
  ${TFLITE_SRC}/micro/kernels/zeros_like.cc
  ${TFLITE_SRC}/micro/recording_simple_memory_allocator.cc
  ${TFLITE_SRC}/micro/system_setup.cc
  ${TFLITE_SRC}/micro/micro_time.cc
  ${TFLITE_SRC}/micro/test_helpers.cc
  ${TFLITE_SRC}/micro/debug_log.cc
  ${TFLITE_SRC}/micro/micro_interpreter.cc
  ${TFLITE_SRC}/micro/micro_string.cc
  ${TFLITE_SRC}/micro/memory_helpers.cc
  ${TFLITE_SRC}/micro/recording_micro_allocator.cc
  ${TFLITE_SRC}/micro/micro_graph.cc
  ${TFLITE_SRC}/micro/micro_allocator.cc
  ${TFLITE_SRC}/micro/all_ops_resolver.cc
  ${TFLITE_SRC}/micro/micro_error_reporter.cc
  ${TFLITE_SRC}/micro/micro_profiler.cc
  ${TFLITE_SRC}/micro/micro_utils.cc
  ${TFLITE_SRC}/micro/simple_memory_allocator.cc
  ${TFLITE_SRC}/micro/memory_planner/linear_memory_planner.cc
  ${TFLITE_SRC}/micro/memory_planner/greedy_memory_planner.cc
  ${TFLITE_SRC}/c/common.c
  ${TFLITE_SRC}/core/api/error_reporter.cc
  ${TFLITE_SRC}/core/api/flatbuffer_conversions.cc
  ${TFLITE_SRC}/core/api/op_resolver.cc
  ${TFLITE_SRC}/core/api/tensor_utils.cc
  ${TFLITE_SRC}/kernels/internal/quantization_util.cc
  ${TFLITE_SRC}/kernels/kernel_util.cc
  ${TFLITE_SRC}/schema/schema_utils.cc
  ${TFLITE_SRC}/c/common.c
  ${TFLITE_SRC}/core/api/error_reporter.cc
  ${TFLITE_SRC}/core/api/flatbuffer_conversions.cc
  ${TFLITE_SRC}/core/api/op_resolver.cc
  ${TFLITE_SRC}/core/api/tensor_utils.cc
  ${TFLITE_SRC}/kernels/internal/quantization_util.cc
  ${TFLITE_SRC}/kernels/kernel_util.cc
  ${TFLITE_SRC}/schema/schema_utils.cc)

target_include_directories(tflite_micro PUBLIC
  $ENV{TF_PATH}
  ${TFLITE_SRC}/micro/tools/make/downloads/gemmlowp
  $ENV{TF_PATH}/flatbuffers/include
  ${TFLITE_SRC}/micro/tools/make/downloads/ruy)
